Lesson 7
mrDurandall/GB_Django_1 pull request #7
Opened 2021-09-01 17:16 UTC by mrDurandall

Выполнены все задания

2021-09-02 08:39 UTC, Vokler requested changes

2021-09-02 08:39 UTC, Vokler commented on admins/forms.py
> +    category = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'form-control py-4',
Так как у нас верстка на Bootstrap, то нужно добавить еще один класс для select `form-select`
https://getbootstrap.com/docs/5.1/forms/select/#default

В итоге так должно быть:
`category = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'form-select form-control'}...`

2021-09-02 08:39 UTC, Vokler commented on admins/forms.py
> +    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input',
А для изображения попробуйте поменять css классы, основываясь на этой документации:
https://getbootstrap.com/docs/5.1/forms/form-control/#file-input

2021-09-02 16:03 UTC, mrDurandall commented on admins/forms.py
> +    category = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'form-control py-4',
Тут всё сработало

2021-09-02 16:03 UTC, mrDurandall commented on admins/forms.py
> +    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input',
Здесь тоже получается, но сама форма выбора файла почему-то выглядит криво. Но это уже надо вникать в Bootstrap. А это в задачу нашего курса не входит :)

2021-09-03 08:29 UTC, Vokler approved these changes

2021-09-03 08:29 UTC, merged